backend:
  name: test-repo

media_folder: static/assets
public_folder: assets

collections:
  - name: yrsingh1223
    repo: yrsingh1223/codeblob
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
